apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-login-app
  template:
    metadata:
      labels:
        app: java-login-app
    spec:
      containers:
        - name: java-login-app
          image: us-central1-docker.pkg.dev/java-multi-tier/java-login/java-login-app:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://10.172.0.3:3306/UserDB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: java-login-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: java-login-db
                  key: password
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-login-app
spec:
  type: LoadBalancer
  selector:
    app: java-login-app
  ports:
    - port: 80
      targetPort: http